Первое задание на проверку
js-tasks-ru/jsbasic-20220519_danilyarema pull request #2
Opened 2022-05-24 14:35 UTC by Hydra715

2022-05-24 14:36 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-24 19:22 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-25 07:15 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-25 07:25 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-25 07:29 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-05-25 09:12 UTC, SinimaWath requested changes

2022-05-25 09:12 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  if (( name !== null) && (name.length > 3) && (name !== undefined) && (!name.includes(' '))) {
- Слишком много лишних скобок
- проверку name !== null && name !== undefined - можно упростить до: `Boolean(name)`
- Можно не писать if, если твое выражение и так возвращает true/false: `return Boolean(name) && name.length > 3 && !name.includes(' ')`

2022-05-25 13:45 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-05-26 11:13 UTC, SinimaWath approved these changes

2022-05-26 11:13 UTC, merged